name: Deploy to cloud run
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
        
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/959426188245/locations/global/workloadIdentityPools/github-action-pool-1/providers/github-action-provider-1'
          service_account: 'artifact-repository-access@roomr-222721.iam.gserviceaccount.com'
      
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web 
      

      - name: Checkout Web Server
        uses: actions/checkout@v3
        with:
          repository: sneyd321/flutter_flask_web_server
          path: web-server

      - name: Copy files into server
        run: |
          cp -r build/web web-server/templates
          cd web-server
          cp templates/firebase-messaging-sw.js static/firebase-messaging-sw.js
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/roomr-222721/roomr-docker-repo/roomr-tenant .
          docker push us-central1-docker.pkg.dev/roomr-222721/roomr-docker-repo/roomr-tenant
          gcloud run deploy roomr-tenant --region=us-central1 --image us-central1-docker.pkg.dev/roomr-222721/roomr-docker-repo/roomr-tenant --allow-unauthenticated
          
        

     
     

